{% set version = "0.30.0" %}

package:
  name: asyncpg-stubs
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/asyncpg-stubs/asyncpg_stubs-{{ version }}.tar.gz
  sha256: 8bfe20f1b1e24a19674152ec9abbcc2df72c01e78af696f44fc275d56fe335ba

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.0.0,<2
    - python {{ python_min }}
  run:
    - asyncpg >=0.30,<0.31
    - python >={{ python_min }}
    - typing_extensions >=4.7.0,<5.0.0

test:
  requires:
    - pip
    - mypy
    - python {{ python_min }}
  commands:
    - pip check
    - mypy -p asyncpg

about:
  home: https://github.com/bryanforbes/asyncpg-stubs
  summary: asyncpg stubs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
