{% set version = "0.29.1" %}

package:
  name: asyncpg-stubs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asyncpg-stubs/asyncpg_stubs-{{ version }}.tar.gz
  sha256: 686afcc0af3a2f3c8e393cd850e0de430e5a139ce82b2f28ef8f693ecdf918bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - asyncpg >=0.29,<0.30
    - python >=3.8.0
    - typing_extensions >=4.7.0,<5.0.0

test:
  commands:
    - pip check
    - mypy -p asyncpg
  requires:
    - pip
    - mypy

about:
  home: https://github.com/bryanforbes/asyncpg-stubs
  summary: asyncpg stubs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
