# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.31.2"
  python_check_max: "3.14"

package:
  name: asyncpg-stubs
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/asyncpg-stubs/asyncpg_stubs-${{ version }}.tar.gz
  sha256: 0cb46152f70d1f42f1e1b1dd0d9d9fa573fa896abb1796feeea18b91e113438d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=2.0.0,<3.0.0
    - python ${{ python_min }}.*
  run:
    - asyncpg >=0.31,<0.32
    - python >=${{ python_min }}
    - typing_extensions >=4.13.0,<5.0.0

tests:
  - package_contents:
      site_packages:
        - asyncpg-stubs/__init__.pyi
  - python:
      imports: asyncpg
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - mypy
    script:
      - mypy -p asyncpg

about:
  summary: asyncpg stubs
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://pypi.org/project/asyncpg-stubs
  repository: https://github.com/bryanforbes/asyncpg-stubs

extra:
  recipe-maintainers:
    - bollwyvl
